# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20160616_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('date_time_start',),
            },
        ),
    ]
