# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('added',)},
        ),
    ]
