# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20160715_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('songs', models.ManyToManyField(to='rest_api.Song')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
