# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='playlists',
            field=models.ManyToManyField(to='rest_api.Playlist'),
        ),
    ]
